title: Heart and Hands
tagline: forever dedicated to learning and teaching new things

description: Follower of Jehovah and Jesus. Wife and Mom of 2 adult daughters. Full-Stack Web Developer & Network Engineer Trainee. Self-Employed CNA/AHA Instructor, Past Long-Term Care Administrator & Shepherd/Fiber Arts Enthusiast
email: dawnann@heartandhandstraining.com
url: "http://www.heartandhandstraining.com/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
author: Dawn Ann,RN,MBA
share: true

date: 
update: 

categories: [CNA, GOD, WEB, VSA]
permalink: :title/

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-relative-links

# for jekyll allow relative links in md 
relative_links:
  enabled: true
  collections: false

# site info, downloadable?
show_downloads: "false"
google_analytics: UA-100952871-1
google-site-verification: NVpI7rqgj-WpOrDTXTX5EtqDUw57hNfVRYW3SKTUfoQ

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# https://github.com/jekyll/jekyll/pull/1291/commits/35b16f8f9d08cfca7ee6fb70b1c3ae4901d4ffa9
